{{- if .Values.httpRoute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "tinyauth.fullname" . }}-httproute
  labels:
    {{- include "tinyauth.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.httpRoute.parentRefs | nindent 4 }}
  {{- with .Values.httpRoute.hostnames }}
  hostnames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.httpRoute.rules }}
    {{- $rule := . }}
    - {{- omit . "backendRefs" | toYaml | nindent 6 }}
      backendRefs:
        - name: {{ include "tinyauth.fullname" $ }}
          port: {{ $.Values.service.port }}
    {{- end }}
{{- end }}